fn main() {
    let binding_file =
        std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("transcoding.rs");
    bindgen::Builder::default()
        .clang_args(&["-x", "c++", "-std=c++17", "-fvisibility=default"])
        .header("../../vendor/transcoding_wrapper.hpp")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .allowlist_type("Transcoder")
        .allowlist_type("TextureTranscodedFormat")
        .allowlist_type("TextureCompressionMethod")
        .allowlist_function("c_basisu_transcoder_init")
        .allowlist_function("c_ktx2_transcoder_new")
        .allowlist_function("c_ktx2_transcoder_delete")
        .allowlist_function("c_ktx2_transcoder_transcode_image")
        .allowlist_function("c_ktx2_transcoder_get_r_dst_buf")
        .allowlist_function("c_ktx2_transcoder_get_r_dst_buf_len")
        .allowlist_function("c_ktx2_transcoder_get_r_width")
        .allowlist_function("c_ktx2_transcoder_get_r_height")
        .allowlist_function("c_ktx2_transcoder_get_r_levels")
        .allowlist_function("c_ktx2_transcoder_get_r_layers")
        .allowlist_function("c_ktx2_transcoder_get_r_faces")
        .allowlist_function("c_ktx2_transcoder_get_r_target_format")
        .allowlist_function("c_ktx2_transcoder_get_r_is_srgb")
        .opaque_type("Transcoder")
        .bitfield_enum("TextureCompressionMethod")
        .newtype_enum("TextureTranscodedFormat")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(binding_file)
        .expect("Couldn't write bindings!");
}
